### ISSUE TITLE
UVCDAT GUI can't read ACME (CAM) data.

### ISSUE THREAD

**Issue by ThomasMaxwell** [UV-CDAT/uvcdat#859] opened 2014-10-30 18:27 UTC
When I attempt to load a variable from an ACME CAM dataset in the UVCDAT GUI I get the following error.   This is the same issue that we work around in vcs scripts by using 's=f(“T”,squeeze=1) '.  CAM data can be obtained from:
esg.ccs.ornl.gov/esgf-web-fe/metadataview/ACME.cesm.cam4-se.atm.v1%7Cesg.ccs.ornl.gov.html.

#################################################################################

CDMS error: Error on time conversion: invalid hour = 239261039241284857122685270850462023680.000000

CDMS error: Error on time conversion: invalid hour = 239261039241284857122685270850462023680.000000

Traceback (most recent call last):
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 379, in compute
    self.var = self.to_python()
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 238, in to_python
    var = cdmsfile.__call__(varName, **kwargs)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 45, in __call__
    return v(*args, **kwargs)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 155, in __call__
    grid=grid)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/selectors.py", line 176, in unmodified_select
    fetched = result.subRegion(*specifications)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 709, in subRegion
    slicelist = self.reg_specs2slices (speclist)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 1293, in reg_specs2slices
    raise CDMSError, OutOfRange + str(item)
CDMSError: Coordinate interval is out of range or intersection has no data: (9.969209968386869e+36, 9.969209968386869e+36)
ERROR:root:Uncaught exception: "Coordinate interval is out of range or intersection has no data: (9.969209968386869e+36, 9.969209968386869e+36)"
None

**Comment by philrasch** [comment] 2015-02-07 23:36
Charles, if you tell the ACME workflow team, or the ACME software engineering team, or the ACME Atmosphere Team, we could try to fix the problem where it starts rather than finding a workaround (which I really hate). If you dont know where to file it please contact me and I will help sort it out.
Phil Rasch

**Comment by doutriaux1** [comment] 2015-02-08 16:32
@philrasch as far as i mremeber this is because the time dimension does not seem to be actually written into the netcdf file. And therefore it is filed with some sort of random/garbage number (239261039241284857122685270850462023680.000000) which in turns seem to trigger some sort of overflow in the time convertion package. So just setting time to some reasonable value would fix this. 
I'm not 100% positive @painter1 can confirm, but I think these files were coming out of some NCL post-processing script, it might not be an issue any longer.

**Comment by ThomasMaxwell** [comment] 2015-02-09 18:59
Out tester, Savannah, fount the following UVCDAT GUI error using the current master branch.  It has been reproduced in Mac OSX 10.8 and Linux.

To reproduce:

  1.  run UVCDAT gui.
  2.  Load the "clt" variable from the clt dataset.
  3.  Create a Boxfill plot in cell 1.
  4.  Create a Boxfill plot in cell 2.
  5.  Remove cell 2 by reducing the number of rows to "1" using the control on the "Sheet 1" toolbar.
  6.  Use the same control to increase the number of rows to "2".
  7.  Attempt to create another Boxfill plot in cell 2.
  8.  The plot fails with the following exception:

Traceback (most recent call last):
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1282, in compute
    self.cellWidget = self.displayAndWait(QCDATWidget, input_ports)
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/spreadsheet/basic_widgets.py", line 247, in displayAndWait
    return spreadsheetWindow.displayCellEvent(e)
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/spreadsheet/spreadsheet_window.py", line 491, in displayCellEvent
    sheet.setCellByType(row, col, e.cellType, e.inputPorts)
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 326, in setCellByType
    oldCell.updateContents(inputPorts)
  File "/Developer/Projects/EclipseWorkspace/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1388, in updateContents
    if hasattr(self.parent(),"toolBar"):
RuntimeError: wrapped C/C++ object of type QCDATWidget has been deleted

**Comment by aashish24** [comment] 2015-02-12 16:57
Folks, I suggest we provide direct support to read CAM data via VTK-VCS integration. If this sounds reasonable, I will plan on settting up a meeting to discuss the roadmap.

**Comment by ThomasMaxwell** [comment] 2015-02-12 17:09
After building the current master branch on OSX 10.8.5 I get the following error when starting uvcdat.   It results in UVCDAT being unable to load the CDMS package.  Is anyone else seeing this?

2015-02-12 11:52:15,511 CRITICAL:
/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/vistrails/vistrails/core/packagemanager.py, line 542
Initialization of package <codepath uvcdat_cdms> failed and will be disabled
Package 'UVCDAT CDMS' failed to initialize because of the following exceptions:
Traceback (most recent call last):
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/vistrails/vistrails/core/modules/module_registry.py", line 1454, in initialize_package
    self.auto_add_module(module)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/vistrails/vistrails/core/modules/module_registry.py", line 958, in auto_add_module
    return self.add_module(module)
  File "/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/vistrails/vistrails/core/modules/module_registry.py", line 1114, in add_module
    raise MissingBaseClass(baseClass)
MissingBaseClass: Base class has not been registered : Variable

**Comment by painter1** [comment] 2015-02-12 17:33
Could someone state what data file is giving this problem?  Even better, make it available.  A single bad time value is typical of climatologies generated from CAM output with buggy code (often written in NCL).  I've never seen actual CAM output with a bad time value.

**Comment by ThomasMaxwell** [comment] 2015-02-12 17:58
Every ACME CAM file that I have come across displays this problem.   For example, you can use the attached wget script to download some ACME CAM data from http://esg.ccs.ornl.gov<http://esg.ccs.ornl.gov/>.   Then try the following:

>> ncdump -h B1850C5e1_ne30.cam.h0.0152-09.nc
ncdump: B1850C5e1_ne30.cam.h0.0152-09.nc: NetCDF: Unknown file format

-- Tom

**Comment by painter1** [comment] 2015-02-12 18:07
Your attachment didn't make it onto github, so far as I can tell.  Five minutes ago I was using ncdump to look at another file in the same output set, for year-month 0080-09.  ncdump -h works fine.  I wonder whether the problem is with the automated ESGF publishing system.  Also, there is no variable named 'clt'.  The closest that I can see is 'CLDTOT'.

**Comment by ThomasMaxwell** [comment] 2015-02-12 18:17
Yes, sorry, it turns out that the ncdump error was due to a wget error.   I re-downloaded the file and was able to open and view it in UVCDAT without problem.   Ncdump gives the following for the time axis.  It looks to me like the problem has been fixed in the current batch of data.

>> ncdump -c B1850C5e1_ne30.cam.h0.0152-09.nc

netcdf B1850C5e1_ne30.cam.h0.0152-09 {
dimensions:
lat = 257 ;
lon = 512 ;
time = UNLIMITED ; // (1 currently)
nbnd = 2 ;
chars = 8 ;
lev = 30 ;
ilev = 31 ;
Variables:
…
double time(time) ;
time:long_name = "time" ;
time:units = "days since 0001-01-01 00:00:00" ;
time:calendar = "noleap" ;
time:bounds = "time_bnds" ;…
data:
…

 time = 55388 ;

…

**Comment by aashish24** [comment] 2015-02-12 19:19
Just wanted to confirm: is CAM CF compliant?

**Comment by painter1** [comment] 2015-02-12 20:00
Yes.  At least, I've seen a fair amount of CAM output, and I've never seen a CF violation.

CAM doesn't go farther than that, though.  I would really like to see use of the standard_name attribute (where a suitable standard_name is available) but CAM doesn't do that.  I also would like to see more use of the bounds attribute.   But neither is required by the CF Conventions; the conventions just say how these attributes should be used if present.

**Comment by doutriaux1** [comment] 2015-02-21 01:11
should we close this? Moving to 2.3 at least

**Comment by williams13** [comment] 2015-02-21 01:13
I think this is okay.

**Closed** 2015-02-21 01:26 UTC
Labels: cdms2, UVCDAT GUI, VCS
