### ISSUE TITLE
GUI cannot load variable

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcdat#1057] opened 2015-02-20 22:51 UTC
Run the UV-CDAT GUI, e.g.
uvcdat --output=""
In the variable window (upper-right), click on the "+" to add a variable.  Browse for a suitable NetCDF file.  Choose a variable.  Click on "Load".  Then (with a UV-CDAT which I built earlier today) you get an exception in a popup window:
```
Traceback (most recent call last):
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/variable.py", line 591, in defineVarClicked
    self.getUpdatedVarCheck()
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/variable.py", line 630, in getUpdatedVarCheck
    self.getUpdatedVar(tid)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/variable.py", line 729, in getUpdatedVar
    updatedVar = controller.create_exec_new_variable_pipeline(targetId)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1185, in create_exec_new_variable_pipeline
    self.get_var_module(targetId, dummyCell, CDMSPipelineHelper)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 925, in get_var_module
    module = var.to_module(self.vt_controller)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 164, in to_module
    module = Variable.to_module(self, controller, identifier)
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/packages/uvcdat/init.py", line 58, in to_module
    reg.get_descriptor_by_name(pkg_identifier, self.__class__.__name__))
  File "/Users/painter1/bin/uvcdat-2015.02.20/vistrails/vistrails/core/modules/module_registry.py", line 745, in get_descriptor_by_name
    raise MissingPackage(identifier)
MissingPackage: Missing package: gov.llnl.uvcdat.cdms
```

**Comment by ThomasMaxwell** [comment] 2015-02-24 16:33
I'm running into this error when trying to test my merged branch.   Has anyone fixed this yet?
-- Tom

**Comment by doutriaux1** [comment] 2015-02-24 17:17
I think @remram44 is getting close, but once it failed once I think you might have to remove your .uvcdat directory to "fix" it. Not positive about it but it's worth a try.

**Comment by remram44** [comment] 2015-02-24 17:19
Looks like this is caused by the uvcdat_cdms package not being loaded, I assume because of a previous error. I can't tell from this log.
Ping @vvpalav @hgohil2805

**Comment by doutriaux1** [comment] 2015-02-24 19:01
i think https://github.com/UV-CDAT/VisTrails/pull/14 and https://github.com/UV-CDAT/VisTrails/pull/16 fix this. You probably need to remove your .uvcdat though.

**Closed by doutriaux1** 2015-02-24 19:01 UTC
Labels: Bug, Critical, UVCDAT GUI
