### ISSUE TITLE
Can't send an error report from uvcdat 2.0.0 GUI

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/uvcdat#844] opened 2014-10-24 10:15 UTC
I have tried to report the error mentioned in #843, but I got the following traceback when I clicked on *OK* in the *Report Error* window

Note that this traceback appeared in the Calculator pane, and not in a new Report Error window...

```
stack_trace=Traceback+%28most+recent+call+last%29%3A%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fgui%2Fuvcdat%2FcommandLineWidget.py%22%2C+line+597%2C+in+run_command%0A++++tmp+%3D+prj_controller.create_exec_new_variable_pipeline%28varname%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fgui%2Fuvcdat%2Fproject_controller.py%22%2C+line+1185%2C+in+create_exec_new_variable_pipeline%0A++++self.get_var_module%28targetId%2C+dummyCell%2C+CDMSPipelineHelper%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fgui%2Fuvcdat%2Fproject_controller.py%22%2C+line+939%2C+in+get_var_module%0A++++varms.append%28self.get_var_module%28v%2C+cell%2C+helper%2C+var_dict%29%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fgui%2Fuvcdat%2Fproject_controller.py%22%2C+line+948%2C+in+get_var_module%0A++++opvar%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fpackages%2Fuvcdat_cdms%2Fpipeline_helper.py%22%2C+line+235%2C+in+build_variable_operation_pipeline%0A++++op_module+%3D+op_class_inst.to_module%28controller%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fpackages%2Fuvcdat_cdms%2Finit.py%22%2C+line+945%2C+in+to_module%0A++++module+%3D+CDMSVariableOperation.to_module%28self%2C+controller%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fpackages%2Fuvcdat_cdms%2Finit.py%22%2C+line+457%2C+in+to_module%0A++++reg.get_descriptor_by_name%28identifier%2C+self.__class__.__name__%29%29%0A++File+%22%2Fhome%2Fshare%2Funix_files%2Fcdat%2Fversions%2Fcdat_install_uv-2.0.0_x86_64_gcc4_12%2Fvistrails%2Fvistrails%2Fcore%2Fmodules%2Fmodule_registry.py%22%2C+line+745%2C+in+get_descriptor_by_name%0A++++raise+MissingPackage%28identifier%29%0AMissingPackage%3A+Missing+package%3A+gov.llnl.uvcdat.cdms%0A&description=modules%3A+Missing+package%3A+gov.llnl.uvcdat.cdms&source=UV-CDAT&hashed_hostname=0348cd5ec8ea8e6bf1454f5133d8979bfd45286b&comments=See+https%3A%2F%2Fgithub.com%2FUV-CDAT%2Fuvcdat%2Fissues%2F843+for+details&platform_version=2.6.32-504.el6.x86_64&platform=Linux&execution_log=&hashed_username=06c74c524fd72182b5a63d2c9f8dd39f5a0d1f8d&source_version=1.2.1&severity=FATAL
http://uvcdat.llnl.gov/UVCDATUsage/log/add/error/
Traceback (most recent call last):
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/vistrails/vistrails/gui/uvcdat/reportErrorDialog.py", line 87, in sendError
    urlencode(data))
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.0.0_x86_64_gcc4_12/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by doutriaux1** [comment] 2015-02-20 23:25
@mattben what's the status on this?

**Comment by hgohil2805** [comment] 2015-03-05 19:46
http://uvcdat.llnl.gov/UVCDATUsage/log/add/error/

can confirm that I can report the error's fine. Can someone else also check? (although is still prints a lot of extra information https://github.com/UV-CDAT/uvcdat/issues/1088)

**Comment by doutriaux1** [comment] 2015-03-05 20:12
seems to work for me as well closing

**Closed by doutriaux1** 2015-03-05 20:12 UTC
Labels: Bug

**Comment by remram44** [comment] 2015-03-17 17:15
Probable duplicate of #930
