### ISSUE TITLE
problem with opendap file

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1475] opened 2015-08-03 15:05 UTC
I am trying to open a file with opendap:

[7:58am] Jerrys-MBP[/Users/potter]python
Python 2.7.9 (default, May 14 2015, 11:49:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
>>> f=cdms2.open('http://dataserver.nccs.nasa.gov/thredds/ncss/grid/bypass/CREATE-IP/MERRA/mon/atmos/zg.ncml')
Abort

No errors- just "Abort". The address works fine in grads.

Is this supposed to work?

**Comment by ThomasMaxwell** [comment] 2015-08-03 15:30
Jerry,

     I don’t know where you got that URL, but the following should work for CREATE-IP/MERRA (are you trying to access a different version of the dataset?):


 f=cdms2.open('http://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/MERRA/mon/atmos/zg.ncml')


— Tom

**Comment by potter2** [comment] 2015-08-03 15:36
Tom,
I get the same error with your address..
Did you try it on your MAC?

Jerry


On Aug 3, 2015, at 8:30 AM, Thomas Maxwell <notifications@github.com<mailto:notifications@github.com>> wrote:

Jerry,

I don’t know where you got that URL, but the following should work for CREATE-IP/MERRA (are you trying to access a different version of the dataset?):


f=cdms2.open('http://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/MERRA/mon/atmos/zg.ncml')


— Tom

**Comment by ThomasMaxwell** [comment] 2015-08-03 15:39
Works fine for me from my Mac desktop at NASA:


>>> import cdms2

>>> f=cdms2.open('http://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/MERRA/mon/atmos/zg.ncml')

>>> v = f['zg']

>>> v.shape

(432, 42, 361, 540)

>>>

**Comment by doutriaux1** [comment] 2015-08-03 16:51
@potter2 there's currently an issue with netcdf/opendap in master see: https://github.com/Unidata/netcdf-c/issues/122
@dnadeau4 maybe we can try to look at this together.

**Comment by doutriaux1** [comment] 2015-08-03 21:09
see: https://github.com/Unidata/netcdf-c/issues/122 it seems to be related to GUI creating .dodsrc
bad code is at: https://github.com/UV-CDAT/VisTrails/blob/uvcdat-master/vistrails/gui/uvcdat/esgf.py#L186-L214

**Comment by dnadeau4** [comment] 2015-08-03 21:54
@potter2 an temporary solution is to comment out all the CURL mention in your ~/.dodsrc.

#CURL.COOKIEJAR=.dods_cookies
#CURL.SSL.VALIDATE=1
#CURL.SSL.CERTIFICATE=/home/dnadeau/.esg/credentials.pem
#CURL.SSL.KEY=/home/dnadeau/.esg/credentials.pem
#CURL.SSL.CAPATH=/home/dnadeau/.esg/certificates

**Comment by doutriaux1** [comment] 2015-08-03 23:16
yep confirmed:
```
doutriaux1@sofia:[~/build]:[6281]> ctest -j8 -R CDMS_Test_multiple_formats
Test project /Users/doutriaux1/build
    Start 26: CDMS_Test_multiple_formats
1/1 Test #26: CDMS_Test_multiple_formats .......   Passed    0.70 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.71 sec
doutriaux1@sofia:[~/build]:[6282]> mv /Users/doutriaux1/.dodsrc.old /Users/doutriaux1/.dodsrc
doutriaux1@sofia:[~/build]:[6283]> ctest -j8 -R CDMS_Test_multiple_formats
Test project /Users/doutriaux1/build
    Start 26: CDMS_Test_multiple_formats
1/1 Test #26: CDMS_Test_multiple_formats .......***Failed    0.31 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.31 sec

The following tests FAILED:
	 26 - CDMS_Test_multiple_formats (Failed)
Errors while running CTest
```

**Comment by potter2** [comment] 2015-08-04 00:01
I deleted ~/.didscr and then it worked. 

Thanks for finding this!

**Comment by durack1** [comment] 2015-09-02 00:48
@potter2 @doutriaux1 can this be closed?

**Comment by doutriaux1** [comment] 2015-09-02 03:50
no. i am waiting for esgf to be back up to implement a permanent fix that will also work for esgf auth

**Comment by doutriaux1** [comment] 2015-09-18 18:12
partly fixed by https://github.com/UV-CDAT/VisTrails/pull/58

**Comment by dnadeau4** [comment] 2015-09-18 22:25
I looked into  the THREDDS case today.  In CDMS2 it will be some work to return a slice of the array.  The CDMS2 architecture is made to return the **whole array** and there is a verification where each returned axis length match the returned netCDF array shape.  Maybe I can manage something in CDMS3.

**Comment by durack1** [comment] 2015-09-18 23:09
@dnadeau4 this (subsetting commentary) is associated with #1288

**Closed** 2015-09-19 02:25 UTC
Labels: Bug, cdms2, Gatekeeper
