### ISSUE TITLE
saving image error

### ISSUE THREAD

**Issue by devarajun** [UV-CDAT/uvcdat#1326] opened 2015-05-19 15:25 UTC
Hi 
I am using UVCDAT 2.1.0 on Linux PC, OS is Fedora details (`Linux lsce3190.extra.cea.fr 3.19.5-100.fc20.x86_64 #1 SMP Mon Apr 20 19:51:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`).

On UVCDAT  GUI after plotting a spatial plot, I tried to save from spreadsheet (Export sheet--> As a single image, I named it as watertable.png) there is no image file created.
I have got the following error. Can any one help me out?
```
Traceback (most recent call last):
  File "/homel/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/vistrails/vistrails/packages/spreadsheet/spreadsheet_tabcontroller.py", line 426, in exportSheetToSingleImageActionTriggered
    self.currentWidget().exportSheetToImage(filename)
  File "/homel/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 543, in exportSheetToImage
    pix = widget.grabWindowPixmap()
  File "/homel/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/vistrails/vistrails/packages/vtk/vtkcell.py", line 965, in grabWindowPixmap
    uchar = self.saveToPNG(None)
  File "/homel/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1529, in saveToPNG
    self.canvas.png(filename)
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/Canvas.py", line 4730, in png
    return self.backend.png(file,width,height,units,draw_white_background, **args )
  File "/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1373, in png
    if not file.split('.')[-1].lower() in ['png']:
AttributeError: 'NoneType' object has no attribute 'split'
```

After this I tried to save it as pdf, but UVCDAT GUI itself closed and got error as below:
```
QPaintDevice: Cannot destroy paint device that is being painted
/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/bin/uvcdat: line 6: 18082 Segmentation fault      (core dumped) python2.7 $INSTALL_PREFIX/vistrails/vistrails/uvcdat.py $@
```

Thanks for your help! in advance

Dev

**Comment by remram44** [comment] 2015-06-10 14:36
The first issue is a duplicate of #1276; needs fixing. I don't know about the crash though.

**Closed** 2015-06-11 15:17 UTC
Labels: Bug, Duplicate

**Comment by ThomasMaxwell** [comment] 2015-06-11 21:33
I’m getting the following SciPy build error when building the current release source on CentOS 6.6:



[ 76%] Performing configure step for 'SCIPY'

CMake Error at /usr/local/uvcdat/2.2/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure.cmake:56 (message):

  CTEST_FULL_OUTPUT


   Command failed: 1

   '/usr/bin/cmake' '-DCONFIG_TYPE=.' '-DCDAT_USE_SYSTEM_LAPACK:STRING=OFF' '-DLAPACK_LIBRARIES:STRING=/usr/lib64/liblapack.so' '/usr/lib64/libblas.so' '-DBLAS_LIBRARIES:STRING=/usr/lib64/libblas.so' '-P' '/usr/local/uvcdat/2.2/build/CMake/SCIPY_configure_step.cmake'

   From /usr/local/uvcdat/2.2/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure-out.log


  -------------------------------------------------


  Processing scipy/interpolate/interpnd.pyx


  Cythonizing sources


  -------------------------------------------------


   From /usr/local/uvcdat/2.2/build/SCIPY-prefix/src/SCIPY-stamp/SCIPY-configure-err.log


  -------------------------------------------------


  Configuring SCIPY:


  /usr/local/uvcdat/2.2/build/build/SCIPY





  Error compiling Cython file:


  ------------------------------------------------------------


  ...





  cdef extern from "numpy/ndarrayobject.h":


      cdef enum:

          NPY_MAXDIMS





  ctypedef fused double_or_complex:


                                 ^




  ------------------------------------------------------------





  scipy/interpolate/interpnd.pyx:41:32: Syntax error in ctypedef statement


  Traceback (most recent call last):


    File "/usr/local/uvcdat-test/2.2/build/build/SCIPY/tools/cythonize.py", line 198, in <module>

      main()

    File "/usr/local/uvcdat-test/2.2/build/build/SCIPY/tools/cythonize.py", line 194, in main

      find_process_files(root_dir)

    File "/usr/local/uvcdat-test/2.2/build/build/SCIPY/tools/cythonize.py", line 186, in find_process_files

      process(cur_dir, fromfile, tofile, function, hash_db)

    File "/usr/local/uvcdat-test/2.2/build/build/SCIPY/tools/cythonize.py", line 160, in process

      processor_function(fromfile, tofile)

    File "/usr/local/uvcdat-test/2.2/build/build/SCIPY/tools/cythonize.py", line 71, in process_pyx

      raise Exception('Cython failed')


  Exception: Cython failed


  Traceback (most recent call last):


    File "setup.py", line 253, in <module>

      setup_package()

    File "setup.py", line 246, in setup_package

      generate_cython()

    File "setup.py", line 164, in generate_cython

      raise RuntimeError("Running cythonize failed!")


  RuntimeError: Running cythonize failed!


  CMake Error at

  /usr/local/uvcdat/2.2/build/CMake/SCIPY_configure_step.cmake:58 (message):


    Error in config of SCIPY

**Comment by remram44** [comment] 2015-06-11 21:52
@ThomasMaxwell please open a different issue if needed
