### ISSUE TITLE
Isoline labels broken

### ISSUE THREAD

**Issue by potter2** [UV-CDAT/uvcdat#1132] opened 2015-03-08 01:57 UTC
When I plot an isoline in a latitude by level plot then add labels no labels are produced instead lines across the plot. It looks like nobody tried to add isoline labels to
![isoline](https://cloud.githubusercontent.com/assets/2963950/6544125/63ddfbe2-c4f3-11e4-951a-5c9ebe29298b.png)
 a plot like this.

**Comment by aashish24** [comment] 2015-03-12 15:13
@potter2 wasn't this specific to a particular projection?

**Comment by potter2** [comment] 2015-03-12 15:19
This happen in a latitude-level plot. I posted an example

Jerry

Sent from my iPhone

On Mar 12, 2015, at 8:13 AM, Aashish Chaudhary <notifications@github.com<mailto:notifications@github.com>> wrote:


@potter2<https://github.com/potter2> wasn't this specific to a particular projection?

**Comment by dlonie** [comment] 2015-03-12 16:49
Can you post an example with instructions to reproduce? That will make this much, much easier to address.

Also, does the isoline (without labels) work as expected?

**Comment by doutriaux1** [comment] 2015-03-12 17:40
@dlonie you need data with levels look into sample data some file starting with ta_ then select one time and one longitude to end up with level and latitude only. That should do it

**Comment by potter2** [comment] 2015-03-12 17:50
Thanks Charles,
I'm not at my computer right now.

Jerry

Sent from my iPhone

On Mar 12, 2015, at 10:40 AM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@dlonie<https://github.com/dlonie> you need data with levels look into sample data some file starting with ta_ then select one time and one longitude to end up with level and latitude only. That should do it

**Comment by potter2** [comment] 2015-03-12 22:06
As Charles said,
Select any 3D variable, select one longitude and all levels and all latitudes. Then plot with isolines. This seems to work, then select the pencil and select "draw labels” then apply - here you can see the problem.

here is a video of the steps:
https://www.dropbox.com/s/a0pnixb1qlzd5ab/labels_problem.mov?dl=0

Jerry


On Mar 12, 2015, at 9:49 AM, David Lonie <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post an example with instructions to reproduce? That will make this much, much easier to address.

Also, does the isoline (without labels) work as expected?

—
Reply to this email directly or view it on GitHub<https://github.com/UV-CDAT/uvcdat/issues/1132#issuecomment-78523921>.

--
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by dlonie** [comment] 2015-03-13 12:34
Excellent -- thanks! I'll have a look.

**Comment by dlonie** [comment] 2015-03-17 19:18
I tried this using `ta` from `sample_data/ta_ncep_87-6-88-4.nc` in a 'quick' isoline plot with labels, and got the following:

![isolabels](https://cloud.githubusercontent.com/assets/58744/6695586/be22d588-ccb8-11e4-8a0e-1db37ecf1283.png)

Does this sample file work on your system?

**Comment by potter2** [comment] 2015-03-17 19:24
Have you tried the latitude-level plot?

Sent from my iPhone

On Mar 17, 2015, at 12:19 PM, David Lonie <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried this using ta from sample_data/ta_ncep_87-6-88-4.nc in a 'quick' isoline plot with labels, and got the following:

[isolabels]<https://cloud.githubusercontent.com/assets/58744/6695586/be22d588-ccb8-11e4-8a0e-1db37ecf1283.png>

Does this sample file work on your system?

**Comment by dlonie** [comment] 2015-03-17 19:38
Ah, I see, I was missing some of the config options when loading the variable. It looks like the labels are getting scaled along with the data. Let me see what I can come up with.

**Comment by doutriaux1** [comment] 2015-03-17 23:09
@dlonie I think that's another issue actually, @potter2 had a good plot to start with, but then "clicked" edit and got the bad plot. Is that right @potter2?

**Comment by potter2** [comment] 2015-03-17 23:23
Yes, when I “apply” the “label" contours is when the horizontal lines appear
On Mar 17, 2015, at 4:09 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@dlonie<https://github.com/dlonie> I think that's another issue actually, @potter2<https://github.com/potter2> had a good plot to start with, but then "clicked" edit and got the bad plot. Is that right @potter2<https://github.com/potter2>?

—
Reply to this email directly or view it on GitHub<https://github.com/UV-CDAT/uvcdat/issues/1132#issuecomment-82635049>.

--
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by potter2** [comment] 2015-03-17 23:27
Here is a video of what I did:

https://www.dropbox.com/s/a0pnixb1qlzd5ab/labels_problem.mov?dl=0


On Mar 17, 2015, at 4:09 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@dlonie<https://github.com/dlonie> I think that's another issue actually, @potter2<https://github.com/potter2> had a good plot to start with, but then "clicked" edit and got the bad plot. Is that right @potter2<https://github.com/potter2>?

—
Reply to this email directly or view it on GitHub<https://github.com/UV-CDAT/uvcdat/issues/1132#issuecomment-82635049>.

--
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by dlonie** [comment] 2015-03-18 19:26
UVCDAT/VTK@287b9443cf2622fcec69876f8aacb41b8bfb357b should fix this. The fix is in uvcdat-master now, so a fresh build should work as expected.

**Comment by potter2** [comment] 2015-03-18 19:48
Thanks,
I’ll build it and try it now

Jerry

On Mar 18, 2015, at 12:26 PM, David Lonie <notifications@github.com<mailto:notifications@github.com>> wrote:


UVCDAT/VTK@287b944<https://github.com/UVCDAT/VTK/commit/287b9443cf2622fcec69876f8aacb41b8bfb357b> should fix this. The fix is in uvcdat-master now, so a fresh build should work as expected.

—
Reply to this email directly or view it on GitHub<https://github.com/UV-CDAT/uvcdat/issues/1132#issuecomment-83129950>.

--
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov<mailto:gerald.potter@nasa.gov>
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by dlonie** [comment] 2015-04-08 14:26
Closing as the patch fixed this for me. Reopen if the problem persists.

**Closed by dlonie** 2015-04-08 14:26 UTC
Labels: VCS
