### ISSUE TITLE
Editing a label, rotate to ~311 degrees, open font menu -> segfault

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcdat#1093] opened 2015-03-02 18:15 UTC
When you edit a text object and rotate it to somewhere around 311 degrees and open the font menu, we segfault.

Discussion on #1081

**Comment by doutriaux1** [comment] 2015-03-02 18:25
@dlonie it might be VTK issue so assigning to you.

**Comment by chaosphere2112** [comment] 2015-03-03 21:42
@dlonie Any update on this? I'm probably going to be doing a workaround for this issue tomorrow if nothing looks promising.

**Comment by dlonie** [comment] 2015-03-04 14:23
@chaosphere2112 I haven't had a chance to look into it yet. Feel free to do a workaround.

**Comment by aashish24** [comment] 2015-03-12 15:15
Moving this to 2.3 for now as we have the workaround for 2.2

**Comment by chaosphere2112** [comment] 2015-03-12 15:16
:+1:

**Comment by dlonie** [comment] 2015-05-01 15:49
Is this still an issue? I'm trying to reproduce, but can you clarify what you mean by "font menu"? I don't see this. So far I've:

1) Plotted clt on default boxfill
2) Clicked the pencil to start editing
3) Select text
4) Show angle
5) Adjust to 311 degrees

Not sure what's next.

**Comment by chaosphere2112** [comment] 2015-05-01 15:51
@dlonie I removed the font menu (which was a button you could click in the configure menu to open a list of all of the fonts available, styled using those fonts) and replaced with one button you click through to cycle which font you're using. It's not ideal, but it'll work for now. We can look into this further in a week or two.

**Comment by dlonie** [comment] 2015-05-01 15:53
Aha, that would explain it :dancer: 

Let me know when this is ready to look into again.

**Comment by dlonie** [comment] 2015-05-01 15:57
Actually, I just triggered a segfault by clicking through the available font faces. I'll see if this is the same one (need to recompile so python's unicode matches my debugger...)

**Comment by chaosphere2112** [comment] 2015-05-01 15:57
Ok, cool; let me know if you find anything.

**Comment by dlonie** [comment] 2015-05-01 17:18
It is the same crash. Interesting, because the docs say face->size is always initialized for new fonts (and indeed, the freetype sources do this). I'll poke around a bit and see what I can find.

**Comment by dlonie** [comment] 2015-05-01 19:01
Found the issue:

The FreeType library sets `face->size` to an appropriate FT_Size object when it loads the font face. However, once it is loaded into FreeType's internal caching system, it deletes this object and sets `face->size` to 0. This modified version is what FreeType gives to VTK when we request a face from the cache manager.

Then we query the kerning information, and an unguarded dereference of `face->size` occurs, triggering the segfault.

I'm going to put this back on the backburner for now. I have some pending changes to VTK that add DPI awareness to the toolkit, and part of these changes involve rewriting how we access cached font faces. The new implementation actually looks up FT_Size objects in the cache (rather than faces), so we will definitely have valid sizes after that change lands.

I just got the greenlight to work on that feature again, and I should have this in upstream VTK within a few weeks. After that, we can bump VTK/uvcdat-master and this problem should disappear.

I'll leave this bug open so I remember to test then....

**Comment by chaosphere2112** [comment] 2015-05-01 19:10
Cool! When I did my spelunking, that was my best guess as to the root cause.

**Comment by doutriaux1** [comment] 2015-09-02 18:41
@chaosphere2112 should we close that?

**Comment by chaosphere2112** [comment] 2015-09-02 18:43
@dlonie Did the fix get merged into VTK?

**Comment by dlonie** [comment] 2015-09-02 19:48
@chaosphere2112 It did. Want to try removing your workaround and make sure it's working?

UV-CDAT/VTK@07e728b904e5a894376b2b8381a1f6f71391bf6a is the patch that should fix it.

**Comment by chaosphere2112** [comment] 2015-09-02 20:30
Yup, I'll give this a test and report back.

**Comment by doutriaux1** [comment] 2015-09-04 00:37
Fixed by #1514

**Closed by doutriaux1** 2015-09-04 00:37 UTC
Labels: VCS, VTK
