### ISSUE TITLE
Contour labels are don't show up in exported file (PNG or PDF)

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1626] opened 2015-10-21 20:19 UTC
I sent a example code to @dlonie . Originally submitted by Jerry.

**Comment by dlonie** [comment] 2015-10-22 19:40
@aashish24 PNG works, always has -- there are several tests that have exercised this functionality since the feature was added. If there is an issue with PNG, I'll need more information on how to reproduce it.

Some bits were missing for vector export, should be fixed by UV-CDAT/VTK#10.

**Comment by dlonie** [comment] 2015-10-22 19:47
Patch merged.

**Closed by dlonie** 2015-10-22 19:47 UTC

**Comment by aashish24** [comment] 2015-10-24 04:55
thanks @dlonie for taking care of this quicly! Awesome stuff!!!!!
