### ISSUE TITLE
Cdscan on 2 cdscan generated xml files fails (forecast extra args related)

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#124] opened 2013-02-22 23:42 UTC
Generate xml file using cdscan, say historical and picontrol on cmip5 data.
Use cdscan to join two xml files you get error relating to invalid number of args to unpack. This is due to forecast modifications that are not pickedp up
Line 834 632
Once adjusted the unpack accordingly I still somehow stumble on yet another forecast issue: calendar is not set to None for time indep vars (latbnds for example)
This is high priority

**Comment by doutriaux1** [comment] 2015-02-21 00:51
@painter1 it's not what you just fixed right?

**Comment by durack1** [comment] 2015-02-21 00:54
@doutriaux1 this might be a good place to drop the query about the https://github.com/UV-CDAT/uvcdat/tree/master/Packages/psql alternative?

**Comment by doutriaux1** [comment] 2015-02-21 01:05
@williams13 do you remember why Bob didn't like psql (other than he didn't design it). I was pretty junior at the time but as a user (that's how long ago) psql was much more intuitive and as far as i remembe rgo handle any dimension. Do you think it could be worth reviving as a companion to cdscan?

**Comment by williams13** [comment] 2015-02-21 01:10
Psql wasn’t done by Bob, it was done by Charlie O’Connor back in the day. Agreed it is more institute. Not sure we (i.e, you) have time for this. We will have someone soon to work on this.

**Comment by painter1** [comment] 2015-02-21 01:18
@doutriaux1 , that's right.  I'm sorry, I forgot about this one.  It may take some time to do anyway.

**Comment by durack1** [comment] 2015-02-21 01:23
@doutriaux1 @williams13 @painter1 I've just created a new issue for this side-discussion (psql and alternatives to completely rewriting cdscan) it's found at #1059

**Comment by doutriaux1** [comment] 2015-02-21 01:25
@williams13 yes I knew it was Charlie's work (which is why I was asking if Bob didn't like it just because he didn't design it or there were other more serious reasons). I agree if you could find someone else to work on reviving this that would be awesome.

**Comment by doutriaux1** [comment] 2015-02-21 01:26
yes that's why I moved it to 2.3

**Comment by doutriaux1** [comment] 2015-02-21 01:28
ok but this issue stays opened.

**Comment by durack1** [comment] 2015-02-21 01:31
@doutriaux1 if this is a dupe of #1059 then you may as well close one or the other.. My thought was that this #124 issue is just a bugfix request for cdscan, rather than a more complicated rewriting of cdscan or reviving of psql..

**Comment by painter1** [comment] 2015-02-23 16:53
reopening because this issue is a bugfix, 1059 is broader, and I haven't fixed the bug yet

**Comment by doutriaux1** [comment] 2016-01-04 21:20
@painter1 we're closing in on 3 years now :stuck_out_tongue_winking_eye:

**Closed** 2016-02-03 19:21 UTC
Labels: 4 - Done, Bug, cdms2
