### ISSUE TITLE
creating pngs in background mode leaks memory

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat#1397] opened 2015-06-16 21:13 UTC
A LOT!!!
```python
for i in range(120):
   x.plot(data,"default","isofill")
   x.png("file_%i.png" % i)
   x.clear()
```
run and look at memory in top.

**Comment by doutriaux1** [comment] 2015-06-16 21:21
@dlonie any idea why the memory could grow when bg=True ? The renWin is different obviously. Could it be VTK related?
Note: I tried to comment out hideGui/showGUI in def png but no luck

**Comment by dlonie** [comment] 2015-06-17 12:12
I'm a bit confused, it doesn't look like the `plot` call in the sample code is using background mode?

In any case, it doesn't look like VTK is holding onto anything in offscreen mode:

```
import gc
gc.enable()
gc.set_debug(gc.DEBUG_LEAK)

def runTest():
    import vtk
    sphere = vtk.vtkSphereSource()

    mapper = vtk.vtkPolyDataMapper()
    mapper.SetInputConnection(sphere.GetOutputPort())

    actor = vtk.vtkActor()
    actor.SetMapper(mapper)

    ren = vtk.vtkRenderer()
    ren.AddActor(actor)

    renWin = vtk.vtkRenderWindow()
    renWin.AddRenderer(ren)

    renWin.OffScreenRenderingOn()
    renWin.SetSize(300, 300)

    renWin.Render()

runTest()
del runTest

gc.collect()

leaks = {}

for i,g in enumerate(gc.garbage):
    t = type(g)
    print "Leak %d: %s @0x%x:\n   %s"%(i, t, id(g), str(g)[:70])
    leaks[t] = leaks.get(t, 0) + 1

for t in leaks:
    print "%7d: %s"%(leaks[t], t)

print len(gc.garbage),"leaks total."
```

```
$ python vtk_offscreen.py 
0 leaks total.
```

Looks like the leaks are on the VCS side of things.

**Comment by doutriaux1** [comment] 2015-06-17 16:35
@dlonie  I'm not quite sure what's going. All @durack1 and I noticed is that if you plot with vcs bg=1 then the process mem size keeps growing. And looking at the code it seems that the only differenc eis this:
```python
    if self.bg:
        self.renWin.SetOffScreenRendering(True)
        self.renWin.SetSize(self.canvas.bgX,self.canvas.bgY)
```

But obviously there must be something else.

**Comment by durack1** [comment] 2015-06-17 16:37
@doutriaux1 @dlonie for perspective, the loop generating these images has ~1700 steps and as it passed the 1000 mark yesterday it was using 50GB! of memory.. So it's not a small leak at all..

**Comment by doutriaux1** [comment] 2015-06-17 16:37
@dlonie also it seems to be coming from the png function not the rendering function.
also a few more options are set on our renWin, not sure if it's matter e.g:
```python
      self.renWin.SetWindowName("VCS Canvas %i" % self.canvas._canvas_id)
      self.renWin.SetAlphaBitPlanes(1)
      ## turning on Stencil for Labels on iso plots
      self.renWin.SetStencilCapable(1)
      ## turning off antialiasing by default
      ## mostly so that pngs are same accross platforms
      self.renWin.SetMultiSamples(0)
```

**Comment by dlonie** [comment] 2015-06-17 17:15
Those additional settings on the renderwindow shouldn't affect the offscreen rendering mechanism. Well, `MultiSampling` _might_, but only if it were non-zero.

What is the memory usage for the following scenarios?

- bg + plot + png
- bg + plot
- plot

Also, have you printed out the leaking objects and compared the results with a single run? The objects with increased leaks may point you to the issue.

**Comment by dlonie** [comment] 2015-06-17 17:18
The 50GB would make sense if the plot map were leaking -- that holds on to all of the plotted datasets as well as the intermediate filter outputs, which would add up very, very quickly.

**Comment by dlonie** [comment] 2015-06-17 17:20
Oh, andby plot map I mean the map returned by `VTKPlots.plot` -- I've noticed that it doesn't get freed in between calls to plot.

**Comment by doutriaux1** [comment] 2015-06-17 17:23
Ok I'll run your runTest and print the leaked object in bg vs not in bg, that should point us in the right direction. Thanks.

**Comment by doutriaux1** [comment] 2015-06-17 17:28
@dlonie yes but why isn't it cleaned up ONLY when plotting in bg mode? That part is really odd.

**Comment by durack1** [comment] 2015-06-17 17:46
@dlonie would a well placed `gc.collect()` within the loop help here, or will these things persist until the code completes?

**Comment by dlonie** [comment] 2015-06-17 17:53
When I was having troubles with it I was doing foreground plots, so I don't think fg/bg really matters for that particular leak.

Garbage collection should happen automatically by the interpreter as-needed. I doubt it's an issue of delayed collection -- given the plethora of other leaks occurring in vcs, it's more likely a reference counting problem (`gc.collect()` won't help if the reference counts are off or there are circular dependencies).

**Comment by doutriaux1** [comment] 2015-06-17 19:09
actually, it does matter, we watch the process go for a while with @durack1 and the memory only grows when using bg=1.

**Comment by dlonie** [comment] 2015-06-17 19:21
Must be a different leak then. I was seeing that dictionary leak in
foreground mode,

On Wed, Jun 17, 2015 at 3:09 PM, Charles Doutriaux <notifications@github.com

**Comment by durack1** [comment] 2015-06-18 00:23
@dlonie @doutriaux1 just FYI.. I ran this for one year, so 48 steps (I'm looping through a bunch of variables) and for this with `bg=True` I hit ~2.4GB, with `bg=False` I hit ~240MB so it does appear to be an issue with the `background` operation

**Comment by dlonie** [comment] 2015-06-18 14:16
@durack1 Thanks for the numbers, that is troubling indeed.

I'm hesitant to say VTK is at fault here, since 

1) I don't see any leaks from a pure VTK application that does background rendering
2) VTK has had much more testing and development than UV-CDAT over the last 20 years, and is tested nightly for memory leaks with valgrind
3) UV-CDAT is known to leak lots of memory

So my suspicion is that something in VCS is holding onto application state in-between calls to `plot`. If you can come up with a script that demonstrates the issue without using VCS (e.g. a pure VTK reproduction of the issue) I'll be happy to track any issues down on our side. Until then, this is most likely a VCS issue.

**Comment by doutriaux1** [comment] 2015-06-18 16:05
@dlonie can you try to add the vtkpngwriter to your bit of coe above, just to make sure. Thanks.

**Comment by durack1** [comment] 2015-06-18 21:12
@dlonie does this output mean anything to you..

```
processing: 1883-09 sic bc <- print output from my script
processing: 1883-10 sic bc
processing: 1883-11 sic bc
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  551681
  Current serial number in output stream:  551681
```

I'll run this code again with some timing turned on, it seems like things really grind to a halt and slow down remarkably when reusing the same canvas from `x = vcs.init()`

**Comment by aashish24** [comment] 2015-06-18 21:15
@dlonie let's try adding vtkpngwriter as @doutriaux1 suggested. That will help. May be we can give it to @sankhesh

**Comment by dlonie** [comment] 2015-06-19 13:43
@durack1 Nope, haven't seen that before. I remember we were having problems with the some template objects growing out of control when reusing a canvas for animations, causing a similar slowdown/memory leak.

@doutriaux1 @aashish24 Rebuilding to rerun w/ png writer now.

**Comment by dlonie** [comment] 2015-06-19 16:31
```
import gc
gc.enable()
gc.set_debug(gc.DEBUG_LEAK)

def runTest():
    import vtk
    sphere = vtk.vtkSphereSource()

    mapper = vtk.vtkPolyDataMapper()
    mapper.SetInputConnection(sphere.GetOutputPort())

    actor = vtk.vtkActor()
    actor.SetMapper(mapper)

    ren = vtk.vtkRenderer()
    ren.AddActor(actor)

    renWin = vtk.vtkRenderWindow()
    renWin.AddRenderer(ren)

    renWin.OffScreenRenderingOn()
    renWin.SetSize(300, 300)

    renWin.Render()

    w2img = vtk.vtkWindowToImageFilter()
    w2img.SetInput(renWin)
    w2img.SetInputBufferTypeToRGBA()

    writer = vtk.vtkPNGWriter()
    writer.SetInputConnection(w2img.GetOutputPort())
    writer.SetFileName("test-output.png")
    writer.Write()

runTest()
del runTest

gc.collect()

leaks = {}

for i,g in enumerate(gc.garbage):
    t = type(g)
    print "Leak %d: %s @0x%x:\n   %s"%(i, t, id(g), str(g)[:70])
    leaks[t] = leaks.get(t, 0) + 1

for t in leaks:
    print "%7d: %s"%(leaks[t], t)

print len(gc.garbage),"leaks total."
```

```
$ python vtk_offscreen.py 
0 leaks total.
```

**Comment by durack1** [comment] 2015-06-19 17:14
@dlonie @doutriaux1 not sure this info below is totally related to the `bg=1` issue title, but just for completeness I've currently got a long run underway and have added in some diagnostics to query time taken through each loop iteration and memory footprint of the process, the code looks like (I've trimmed out the extraneous cdms2.open/close, print and string assignment etc calls for brevity):

```
counter = 1
for var in ['sic','sst']:
    ...
    x           = vcs.init()
    for data in ['obs','bcs']:
        ...
        for count,y in enumerate(range(1870,2013)):
            ...
            for m in range(12):
                startTime = time.time()
                ...
                x.plot(title,bg=bg)
                x.plot(s1,t1,iso,bg=bg); #,ratio="autot"); #,vtk_backend_grid=g)
                x.plot(diff,t2,iso2,bg=bg); #,ratio="autot") ; #,vtk_backend_grid=g)
                x.plot(s2,t3,iso,bg=bg); #,ratio="autot") ; #,vtk_backend_grid=g)
                ...
                x.png(fileName)
                x.clear()
                endTime = time.time()
                ...
                print counterStr,printStr,varName.ljust(6),BC,timeStr,memStr
                counter = counter+1
            ...
            gc.collect() ; # Attempt to force a memory flush
        ...
        x.ffmpeg(os.path.join(outPath,outMP4File),outFiles,rate=5,bitrate=2048); #,options=u'-r 2') ; # Rate is frame per second - 1/2s per month
    x.clear()
```
So the `print` statement prints out the following - just as an aside the `x.ffmpeg` call occurs every 1716 steps, so the memory growth and slowdown has not much to do with this:
```
00001 processing: 1870-01 sic     Time: 04.093 secs; Max mem: 0.238 GB
...
00150 processing: 1882-06 sic     Time: 06.176 secs; Max mem: 0.255 GB
...
00300 processing: 1894-12 sic     Time: 10.063 secs; Max mem: 0.261 GB
...
00500 processing: 1911-08 sic     Time: 15.334 secs; Max mem: 0.280 GB
...
01000 processing: 1953-04 sic     Time: 31.086 secs; Max mem: 0.320 GB
...
01500 processing: 1994-12 sic     Time: 48.595 secs; Max mem: 0.352 GB
...
02000 processing: 1893-08 sic    bc Time: 68.674 secs; Max mem: 0.389 GB
...
```

**Comment by dlonie** [comment] 2015-06-19 17:29
You can try profiling the code and looking at where it's spending all that extra time -- that's how we tracked down the template issue. I'll see if I can dig up some resources.

**Comment by dlonie** [comment] 2015-06-19 17:35
@durack1 In #715 we had a similar issue with resource leaks and slow-downs from canvas reuse. There's a link in there to the cProfile docs, which can be used to find out exactly where all that extra time is going.

**Comment by durack1** [comment] 2015-06-19 17:38
Ok great thanks @dlonie I'll take a peek at cProfile (https://docs.python.org/2/library/profile.html)

**Comment by durack1** [comment] 2015-06-19 23:44
@dlonie @doutriaux1 does this error output mean anything to you:
```
QTextCursor::setPosition: Position '6468302' out of range
QTextCursor::setPosition: Position '13178970' out of range
QTextCursor::setPosition: Position '19936653' out of range
QTextCursor::setPosition: Position '26571249' out of range
QTextCursor::setPosition: Position '15571' out of range
QTextCursor::setPosition: Position '15571' out of range
QTextCursor::setPosition: Position '15581' out of range
```

**Comment by dlonie** [comment] 2015-06-22 12:33
`QTextCursor` is a Qt object that's used to represent the cursor location in a text document. Sounds like a UI issue.

**Comment by doutriaux1** [comment] 2015-06-22 15:27
Qt code! How is that even possible? Thanks @durack1 I start from there...

**Comment by durack1** [comment] 2015-06-22 16:14
@doutriaux1 it would seem to be related to the `title` object, which isn't showing up on the plots..

**Comment by doutriaux1** [comment] 2015-06-24 18:32
by the way I just tested this with x.pdf instead of x.png and the memory doesn't go crazy. So it "seems" to be vtkpngwriter related.

**Comment by durack1** [comment] 2015-06-24 18:34
@doutriaux1 you beat me to it..

**Comment by doutriaux1** [comment] 2015-08-27 17:54
@aashish24 this is very important. Assiging to you I think you dais you were looking into it.

**Comment by aashish24** [comment] 2015-10-15 01:37
@doutriaux1 I am going to verify if VTK is the culprit as discussed.

**Comment by durack1** [comment] 2015-11-18 23:40
@chaosphere2112 you indicated you found and fixed a bug with `pngs` being created - related to on screen rendering if I'm not mistaken.. Is that fix in `master`? And if so I wonder if the problem above might now be mysteriously fixed...?

**Comment by chaosphere2112** [comment] 2015-11-18 23:46
@durack1 That was in the GUI; I'll do a quick check to see if anything is being leaked in python for this, or if it's in VTK.

**Comment by durack1** [comment] 2015-11-18 23:47
@chaosphere2112 ok great.. I've just been running some code that provided the numbers above using `2.4.0rc1` and was curious if `bg=True` was safe to try again..

**Comment by chaosphere2112** [comment] 2015-11-19 00:42
Here's a quick rundown of iterating over `clt` in foreground mode W.R.T. memory leaks...

![graphs](https://cloud.githubusercontent.com/assets/718512/11259001/fe7d243c-8e12-11e5-9ff7-596ba7df6981.png)

Memory is measured in MB, # python objects is measured by `len(gc.get_objects())`, time is in milliseconds

Background mode is quite similar, leaks are a little slower.

It appears that the number of python objects is relatively consistent, but the total amount of memory is increasing (slowly, towards the end). That makes me think the leak is in VTK; I'll do more instrumentation on that tomorrow.

**Comment by durack1** [comment] 2015-11-19 00:53
@chaosphere2112 `~280ms` per plot!?! I need to use what you're using.. I'm getting `~3000ms` or more..

It still appears that a slow continuing leak is occurring, I've just run some updated numbers (using `2.4.0rc1`) at #1424 - I'd be happy to test `master` once things settle down, tomorrow @doutriaux1?

**Comment by doutriaux1** [comment] 2016-01-04 19:43
@aashish24 we failed to address this! Moving to 2.6

**Comment by durack1** [comment] 2016-01-07 17:11
@doutriaux1 @chaosphere2112 should this be a `2.4.1` milestone - it's a pretty nasty one that should be fixed pronto!

**Comment by doutriaux1** [comment] 2016-01-07 17:15
will see. 2.4.1 is mainly for fast climo

**Comment by durack1** [comment] 2016-01-07 17:20
It would be nice to get this fixed next month.. The memory usage and slowdown is something that should be fixed with a high priority I believe..

**Comment by durack1** [comment] 2016-03-04 22:57
@danlipsa @doutriaux1 pinging you here

**Comment by aashish24** [comment] 2016-03-24 23:40
I am looking into this. FIrst will verify if the vtk is the culprit here.

**Comment by durack1** [comment] 2016-03-24 23:42
@aashish24 great! It's a nasty bug that has made me have to write all kinds of garbled code to get around the leak.. This would be a huge improvement for useability

**Comment by danlipsa** [comment] 2016-05-25 20:06
@doutriaux1 @aashish24 This seems to be fixed. I don't get any memory increase on the master branch. Can you confirm that?

**Comment by danlipsa** [comment] 2016-05-25 20:07
This is the script I am using:
import vcs
import cdms2
import sys


x = vcs.init(bg=1, geometry=(1620, 1080))
x.setantialiasing(0)
x.drawlogooff()

f = cdms2.open(vcs.sample_data + "/clt.nc")
data = f('clt')

for i in range(120):
   x.plot(data,"default","isofill")
   x.png("file_%i.png" % i)
   x.clear()

**Comment by danlipsa** [comment] 2016-05-25 21:56
Actually, looking closer the memory does seem to increase, but fairly slowly: for 1500 iterations of the above script from 2.5 GB to 6.3GB. As it runs more, the growth seems to slow down.

**Comment by durack1** [comment] 2016-05-25 22:12
@danlipsa this is consistent with the memory growth in https://github.com/UV-CDAT/uvcdat/issues/1424#issuecomment-168754679, it's slow but noticeable, particularly when you're looping over 1000s of iterations

**Comment by danlipsa** [comment] 2016-06-08 18:03
@chaosphere2112 @aashish24 @doutriaux1 
This is a replay for your comment from Nov 18, 2015 :smile:

The fact that the number of objects is constant does not mean that the leak is not from python.
Attached is a program that eats up memory even if it keeps its number of objects constant.

These are the start and end iterations from this script: a ten fold increase in memory but the same number of objects.


0 ==== Iteration ====
# objects: 3916
VmSize:	   28752 kB
99 ==== Iteration ====
# objects: 3916
VmSize:	  213612 kB
[test-constant-objects.txt](https://github.com/UV-CDAT/uvcdat/files/305398/test-constant-objects.txt)

**Comment by danlipsa** [comment] 2016-06-09 19:11
@doutriaux1 @aashish24 @durack1 There a bug in the VTK, OpenGL, offscreen, Linux. OpenGL2, offscreen does not have it. Not sure if it accounts for what we are seeing here. In my tests this leak is small: 10000 iterations result in 20MB leaked.

http://www.vtk.org/Bug/view.php?id=16744

@durack1 can you run the attached python script in your setup. You were seeing really big leaks.

[vtk-memory.txt](https://github.com/UV-CDAT/uvcdat/files/307735/vtk-memory.txt)

**Comment by aashish24** [comment] 2016-06-09 19:40
@danlipsa this is great progress. Can you call ReleaseGraphicsResources before you delete / remove the renderer?

**Comment by danlipsa** [comment] 2016-06-09 19:50
@aashish24 It makes no difference.

**Comment by durack1** [comment] 2016-06-10 00:26
@danlipsa apologies for the tardy reply, output attached.. The take home is:
```
0 ==== Iteration ====
VmSize:	  999292 kB
...
9990 ==== Iteration ====
VmSize:	 1070188 kB
0 leaks total.
```
[vtk-memory_log.txt](https://github.com/UV-CDAT/uvcdat/files/308129/vtk-memory_log.txt)

**Comment by danlipsa** [comment] 2016-06-10 13:37
@durack1 Can you also run glxinfo where you run your tests and report back the output generated. Thanks Paul.

**Comment by durack1** [comment] 2016-06-10 18:22
@danlipsa here you go:
[glxinfo.txt](https://github.com/UV-CDAT/uvcdat/files/309537/glxinfo.txt)

**Comment by danlipsa** [comment] 2016-06-10 19:03
@durack1 Is this a vmware? What is the host operating system? What is the graphics card? Thanks.

**Comment by durack1** [comment] 2016-06-10 19:09
@danlipsa - the machine is:
```
[durack1@oceanonly ~]$ more /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
[durack1@oceanonly ~]$ uname -a
Linux oceanonly.llnl.gov 2.6.32-573.26.1.el6.x86_64 #1 SMP Tue Apr 12 01:47:01 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```
And I am accessing this through a VNC (mac or windows) client, with the VNC host:
```
[durack1@oceanonly ~]$ Xvnc -help
...
Xvnc TigerVNC 1.1.0 - built Jul 22 2014 06:00:32
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11500000, The X.Org Foundation
```
I'm also having some weird issues with writing `*.png` files using this setup - the same issue documented here https://github.com/UV-CDAT/uvcdat/issues/1424#issuecomment-224652389

**Comment by danlipsa** [comment] 2016-06-10 19:22
@durack1 I see. Makes sense then. You are using a different graphics driver than me (mesa + llvmpipe) which is what I am trying to figure out.
I would be interesting to get to the console of the machine (if you have access to it) and run both the test program and glxinfo. I think you will get similar results - it would be good to check though.

**Comment by danlipsa** [comment] 2016-06-10 19:24
@durack1 That is, use the keyboard and monitor physically attached to oceanonly.

**Comment by durack1** [comment] 2016-06-10 19:28
@danlipsa the machine is physically located in a different building that I don't have access.. I could try an `ssh -Y/X` session and see what gives?

**Comment by danlipsa** [comment] 2016-06-10 19:52
@durack1 That is fine. ssh -X/Y will give you the OpenGL on your local machine. If you have a linux local machine I would be interested in the test results/gxlinfo on that machine, even if you don't run uvcdat there.

**Comment by durack1** [comment] 2016-06-10 20:51
@danlipsa almost all our local machines are now OS X laptops.. What info do you need from these machines locally? Is there another way I can get the same info - querying the system hardware?

**Comment by danlipsa** [comment] 2016-06-13 16:09
@durack1 @doutriaux1 @aashish24 I merged in a fix for the VTK bug
https://gitlab.kitware.com/vtk/vtk/merge_requests/1556
However this does not make a noticeable difference  for uvcdat on my machine. I still see about 1MB per iteration leak for offscreen rendereing. This might be different for a different driver. I think Paul is seeing a much bigger leak per iteration.

**Comment by durack1** [comment] 2016-06-13 16:56
@danlipsa the script that I am using is exposing a very big memory leak, it creates a number of VCS objects before saving this using the pngwriter.. If I can get your merged PR in a build I can rerun my script and report the memory usage.. It seems to expose the issue very quickly throughout the ~8k iterations..

**Comment by durack1** [comment] 2016-06-15 18:43
@danlipsa, @doutriaux1 will pull across your branch for testing locally.. I will run my script against it and see how it compares to `2.4.1` are your changes in a PR in this repo, or a branch?

**Comment by danlipsa** [comment] 2016-06-15 18:45
@durack1 Don't do that yet. I don't think you'll see any difference. I want to look more into this.

**Comment by durack1** [comment] 2016-06-15 18:47
@danlipsa no problem.. Let me know when you want me to kick the tires, it'll take a little time to get the changes into a local build so I can run my script

**Comment by danlipsa** [comment] 2016-06-17 17:16
@aashish24 @durack1 @doutriaux1 I have a new merge request for the VTK bug. The first time the bug it wasn't really fixed.
https://gitlab.kitware.com/vtk/vtk/merge_requests/1574
Waiting for the fix to be merged. @aashish24 :wink: 
This does make a big difference for my uvcdat test. From about 500 MB for 500 iteration the leak is reduced to about 6MB for 500 iterations.

**Comment by durack1** [comment] 2016-06-17 17:19
@danlipsa thanks for the heads up.. This sounds like it, the two order of magnitude drop in memory usage should certainly flow into better behavior in my example script

**Comment by doutriaux1** [comment] 2016-06-20 15:22
That is great! @durack1 I will build a conda for you to test it with.

**Comment by danlipsa** [comment] 2016-06-20 15:27
@doutriaux1 Note, the change is not merged in VTK yet - it is in the review process.

**Comment by doutriaux1** [comment] 2016-06-20 15:46
Can I build against your commit?

**Comment by danlipsa** [comment] 2016-06-20 15:49
@doutriaux1 Yes, you can. It passes all VTK and uvcdat tests.

**Comment by durack1** [comment] 2016-06-21 07:14
@doutriaux1 let me know when I can take a test drive.. I'm curious if this will solve the problem that made things unusable with `bg=1`

**Comment by doutriaux1** [comment] 2016-06-21 19:16
@durack1 it seems that @danlipsa fixed the leak! on `oceanonly` use the conda environment `LEAK` let us know.

**Comment by doutriaux1** [comment] 2016-06-21 19:18
@danlipsa it saves 40Mb per frame on `oceanonly`!

**Comment by durack1** [comment] 2016-06-23 08:58
@doutriaux1 nice! I'll rerun my script next week and see what gives.. And also outline the same diagnostics included [above](https://github.com/UV-CDAT/uvcdat/issues/1397#issuecomment-113579383). An update will also be useful for dealing with #1424 @chaosphere2112

**Comment by doutriaux1** [comment] 2016-06-23 14:09
@durack1 you snoozed too long, it's in master 😉

**Comment by durack1** [comment] 2016-06-23 16:11
@doutriaux1 excellent! Is it in conda nightly?

**Comment by doutriaux1** [comment] 2016-06-23 18:14
yep

**Comment by durack1** [comment] 2016-06-28 18:31
@danlipsa it seems that the `bg=1` memory leak is no longer an issue.

The code iterates through monthly data from 1870-01 to 2012-12 as you can see below, it seems that as a number of arrays are being filled the memory climbs (this is likely an internal python/UV-CDAT behavior), whereas once these variables are being reused there is no memory growth - so 1717 to 3432, 3433 to 5148 and so on:
```
UV-CDAT version:      v2.5.0-576-ge31e2fd
UV-CDAT prefix:       /export/durack1/anaconda2/envs/uvcdatReleaseAlpha
delFudge:             True
Background graphics:  True
00001 processing: 1870-01 sic     Time: 04.149 secs; Max mem: 1.127 GB PyObj#: 0093219;
00002 processing: 1870-02 sic     Time: 03.249 secs; Max mem: 1.561 GB PyObj#: 0093572;
00003 processing: 1870-03 sic     Time: 03.741 secs; Max mem: 1.561 GB PyObj#: 0093624;
...
00040 processing: 1873-04 sic     Time: 03.676 secs; Max mem: 1.562 GB PyObj#: 0095549;
...
00051 processing: 1874-03 sic     Time: 03.910 secs; Max mem: 1.566 GB PyObj#: 0096122;
...
00099 processing: 1878-03 sic     Time: 04.010 secs; Max mem: 1.567 GB PyObj#: 0098622;
...
00110 processing: 1879-02 sic     Time: 03.070 secs; Max mem: 1.571 GB PyObj#: 0099195;
...
00215 processing: 1887-11 sic     Time: 02.999 secs; Max mem: 1.573 GB PyObj#: 0104663;
...
00266 processing: 1892-02 sic     Time: 03.873 secs; Max mem: 1.574 GB PyObj#: 0107300;
...
01716 processing: 2012-12 sic     Time: 08.706 secs; Max mem: 1.619 GB PyObj#: 0182700;
01717 processing: 1870-01 sic    bc Time: 11.680 secs; Max mem: 2.032 GB PyObj#: 0182728;
...
03432 processing: 2012-12 sic    bc Time: 10.099 secs; Max mem: 2.032 GB PyObj#: 0272098;
03433 processing: 1870-01 tos     Time: 10.549 secs; Max mem: 2.093 GB PyObj#: 0272026;
...
05148 processing: 2012-12 tos     Time: 13.383 secs; Max mem: 2.093 GB PyObj#: 0361207;
05149 processing: 1870-01 tos    bc Time: 11.519 secs; Max mem: 2.175 GB PyObj#: 0361424;
...
06795 processing: 2007-03 tos    bc Time: 10.731 secs; Max mem: 2.175 GB PyObj#: 0447012;
...
```
@chaosphere2112 the increase is plot times is still a problem, as are the python objects that continue to accumulate, but that can be solved in #1424 

@danlipsa @doutriaux1 I think you can close this issue

**Comment by aashish24** [comment] 2016-06-28 19:47
yay! great job @danlipsa, thanks @doutriaux1 @durack1

**Comment by danlipsa** [comment] 2016-06-29 01:59
@durack1 @doutriaux1 Thanks for testing! Great to hear the fix works for your test case. I am closing this ...

**Closed by danlipsa** 2016-06-29 01:59 UTC
Labels: 2 - Working <= 5, Bug, Critical, VCS

**Comment by doutriaux1** [comment] 2017-04-05 19:48
@danlipsa @aashish24 we should take a look at this one!
