### ISSUE TITLE
vtk package doesn't load

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvcdat#1017] opened 2015-02-09 20:09 UTC
```
2015-02-09 15:05:58,801 CRITICAL:
/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/
vistrails/core/packagemanager.py, line 542
Initialization of package <codepath vtk> failed and will be disabled
Package 'VTK' failed to initialize because of the following exceptions:
Traceback (most recent call last):
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vi
strails/vistrails/core/modules/module_registry.py", line 1434, in initialize_pac
kage
    package.initialize()
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/core/modules/package.py", line 378, in initialize
    self._init_module.initialize()
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 1164, in initialize
    delayed)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 782, in setAllPorts
    setAllPorts(child, delayed)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 780, in setAllPorts
    addPorts(descriptor.module, delayed)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 754, in addPorts
    addOtherPorts(module, parser.get_other_methods())
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 680, in addOtherPorts
    signatures = get_method_signature(method)
  File "/home/vagrant/builds/60b5589a8e3847dc61a505a34f9ae991dc8f6a5f/install/vistrails/vistrails/packages/vtk/init.py", line 161, in get_method_signature
    tmptmp = doc.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by remram44** [comment] 2015-02-09 20:45
This is caused by __doc__ slots being None on vtk classes.

**Comment by doutriaux1** [comment] 2015-02-09 22:14
@aashish24 @dlonie is it because of the new VTK update? How come we didn't see that before?

**Comment by aashish24** [comment] 2015-02-09 22:57
@remram44  correct me if I am wrong but __doc__ slot is vistrails code?

**Comment by doutriaux1** [comment] 2015-02-09 23:14
@aashish24 i think you're right, but it seems like it is expecting these doc slots to be here in order to generate the vistrails modules or something like that. @remram44 will know better.

**Comment by remram44** [comment] 2015-02-09 23:17
@aashish24: No, the `__doc__` slots on the vtk objects

**Comment by doutriaux1** [comment] 2015-02-09 23:29
I guess you're both right. It's a new issue in VTK (not having doc strings) that ause vistrails to fail because it is expecting it. @remram44 do you know if it's all the VTK objects that are missing these? Or just some new functions? In which case you could probably skip them in vsitrails.

**Comment by aashish24** [comment] 2015-02-11 14:13
@remram44 I was able to reproduce the issue on my mac (fresh build). I am tracking down the changes.

**Comment by aashish24** [comment] 2015-02-12 14:25
@remram44 on second thought. Why do we need to load VTK packages? We don't use VTK directly in VCS 2D or 3D. Can we not disable loading VTK packages? If that's possible it will speed up the load time of the GUI as well.

**Comment by remram44** [comment] 2015-02-12 15:39
I'm not sure the VTK package is used anywhere in UV-CDAT, or has ever been.

**Comment by aashish24** [comment] 2015-02-12 15:50
I think its not used. We only use VCS, CDMS, VCS 3D. Can disable loading VTK packages? If you can push a branch, then I review it. The advantage would be that now the GUI will be much faster to load. If we run into some other issues, then I will help fixing them.

**Comment by dlonie** [comment] 2015-02-17 22:12
Can the initialization code be fixed to handle when `__doc__` returns `None` more gracefully? This is valid in the python object model.

We'll definitely look into what's happening with these missing docstrings, but making this parser more robust would be a good move IMO.

**Comment by remram44** [comment] 2015-02-17 22:15
This is valid in the Python object model but doesn't allow the VTK package to load. This behaves as expected.

**Comment by dlonie** [comment] 2015-02-17 22:17
I'll start looking into this more deeply tomorrow, but can you clarify what is failing? A module shouldn't fail to load because of missing `__doc__`s at the python level -- what is trying to load it and failing?

**Comment by remram44** [comment] 2015-02-17 22:30
This is how the VisTrails vtk wrapper works, it reads the `__doc__` slots to discover input and output ports. There is no way it can do anything without these. Once again, if you don't need these modules, don't enable the vtk package (or even ship it).

**Comment by doutriaux1** [comment] 2015-02-18 02:22
@dlonie @remram44 do we know if the "no doc string" funcs are new ones or old ones that used to be documented but are not anymore?

**Comment by dlonie** [comment] 2015-02-18 17:28
VisTrails is failing to load VTK because the parsers aren't up to date. VTK now allows enum types, the parser is misinterpreting the enums as methods. When it tries to extract the "signature" of the enum (which doesn't make sense), it fails with the exception shown in the issue report.

This is what I was trying to hint at earlier -- if the docstring is not set, it'd be better to gracefully fail and give some feedback on what is missing the docstring.

It's currently failing on the vtkErrorCode::ErrorIds enum, as it seems to be the first enum encountered. Looks like Vistrails needs to have it's parsing logic updated.

**Comment by dlonie** [comment] 2015-02-18 17:32
I can take a stab at disabling VTK in the GUI -- can someone point me to where the Vistrails modules are specified?

**Comment by doutriaux1** [comment] 2015-02-18 17:44
@vvpalav assigning this issue to you as it seems to be a vistrails issue, feel free to reassign to somebody else if that's not your thing.

**Comment by vvpalav** [comment] 2015-02-23 16:39
@dlonie @remram44 are looking into this issue. can you please post any findings?

**Comment by remram44** [comment] 2015-02-23 16:41
@vvpalav: No, I am not. As I said 10min ago via email, this is assigned to you, please check which symbols are missing __doc__ (hopefully these are only named enums) and if we can ignore them safely.

**Comment by dlonie** [comment] 2015-02-23 16:48
@vvpalav See my posts from 2/18 on the issue -- I described the problem there.

Let me know if anything is unclear.

**Comment by remram44** [comment] 2015-02-23 19:41
Filed UV-CDAT/VisTrails#13 please check

**Closed** 2015-02-24 20:10 UTC
Labels: Bug, Gatekeeper, VisTrails
