### ISSUE TITLE
GUI is not tested well

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#585] opened 2014-08-29 05:11 UTC

**Comment by hgohil2805** [comment] 2015-02-26 05:54
Is this something that still needs to be looked at??

**Comment by doutriaux1** [comment] 2015-02-26 23:24
@hgohil2805 it actually got worst since then. There is absolutely no tests for the GUI. Zero, None, NULL.

So yes it is desperately needed!

**Comment by hgohil2805** [comment] 2015-02-26 23:37
Got it. I think we can work on it soon and add some soon. thanks

**Comment by remram44** [comment] 2015-05-16 18:17
Duplicate of #1214

**Closed by remram44** 2015-05-16 18:17 UTC
Labels: Duplicate
