### ISSUE TITLE
cdms2 netcdf use parallel flag fails

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcdat#1593] opened 2015-10-07 18:45 UTC
cdms2 has a flag that turns off parallel IO. I have evidence that it fails.

**Comment by doutriaux1** [comment] 2015-10-07 18:48
@mcenerney1 can you please put a simple script for us to reproduce?

**Comment by mcenerney1** [comment] 2015-10-07 18:50
I did try to make one but failed. I'll continue. But, Denis looked at the code and verified the flag is unused.

**Comment by dnadeau4** [comment] 2015-10-07 18:53
Here is a script that failed

```python
import mpi4py
import cdms2

sz = mpi4py.MPI.COMM_WORLD.Get_size()
rk = mpi4py.MPI.COMM_WORLD.Get_rank()

# All flags are set to OFF for parallel writing
# ----------------------------------------------

cdms2.setNetcdfClassicFlag(0)
cdms2.setNetcdfShuffleFlag(0)
cdms2.setNetcdfDeflateFlag(0)
cdms2.setNetcdfDeflateLevelFlag(0)
cdms2.setNetcdfUseParallelFlag(0)


if rk == 0:
    print rk
    f=cdms2.open("test_mpi_write_2.nc")
    f.close
``

**Comment by dnadeau4** [comment] 2015-10-07 18:54
Here is my solution which works...

in Cdunifmodule.c  we need to check for the cdms_use_parallle before opening  a file with MPIIO.

```C
#ifdef PARALLEL
      int ierr;
      int ncid;

      if(cdms_use_parallel == 1) {
          ierr = nc_open_par(controlpath,mode|NC_MPIIO,MPI_COMM_WORLD,MPI_INFO_NULL,&ncid);
      }
      if((cdms_use_parallel == 0) || (ierr != NC_NOERR )) {
        ierr = nc_open(controlpath,mode,&ncid);
      }
      return ncid;
#else
      ret

```

**Comment by mcenerney1** [comment] 2015-10-07 22:22
do you mean ncmode not mode? also controlpath is undefined.

**Comment by dnadeau4** [comment] 2015-10-07 22:56
mode is passed as a parameter and already contains NC_WRITE or NC_NOWRITE.  Charles is creating a patch and will add this to 2.4.

**Comment by mcenerney1** [comment] 2015-10-07 22:57
Thanks. I modified the wrong part of the code. Is it supposed to be cdopen?

**Comment by mcenerney1** [comment] 2015-10-07 22:59
Mea Culpa!

**Comment by mcenerney1** [comment] 2015-10-08 14:44
This works beautifully!

**Comment by mcenerney1** [comment] 2015-10-08 14:53
It worked for 3 processors, but not 4. The symptoms are the same as before. I suspect the fix needs to be somewhere else also.

**Comment by mcenerney1** [comment] 2015-10-08 18:24
It now works for any number of processors for now. I lost the following mods to cdscan which must
be included in cdscan.
if __name__ == '__main__':
    main(sys.argv)
    from mpi4py import MPI
    comm = MPI.Comm.Get_parent()
    comm.send('cdscan complete')

**Comment by doutriaux1** [comment] 2015-10-08 18:25
@mcenerney1 since it's not in master, let's not close it yet

**Comment by mcenerney1** [comment] 2015-10-08 18:35
OK. We have to resolve the cdms2.setNetcdfUseParallelFlag flag in cdscan.
I confirmed that it is set to 1.  For now it has no effect on the diagnostics.
But it may in the future.

**Comment by dnadeau4** [comment] 2015-10-08 22:46
I created a pull request to set cdms2.setNetcdfUseParallelFlag(0) in cdscan.

**Comment by doutriaux1** [comment] 2016-01-04 19:39
@dnadeau4 is this in?

**Comment by doutriaux1** [comment] 2016-01-04 19:42
looks like yes. @dnadeau4 please reopen if not

**Closed by doutriaux1** 2016-01-04 19:42 UTC
Labels: cdms2
