### ISSUE TITLE
Auto generate release notes

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/uvcdat#913] opened 2014-11-21 22:11 UTC
It seems to me that for all the commit/issue history the release/tags page lacks a lot of interesting detail.
https://github.com/UV-CDAT/uvcdat/releases/tag/2.0.0

There are a couple of attempts it seems to autogenerate detailed issue/commit based release notes which document changes for interested users, I've added a couple of the more interesting pages below:
http://www.mehdi-khalili.com/better-git-release-notes
https://github.com/walmartlabs/generator-release#generating-release-notes
https://github.com/TestStack/TestStack.BDDfy/blob/master/release-notes.md
http://stackoverflow.com/questions/14960674/changelog-generation-from-github-issues

**Comment by durack1** [comment] 2015-02-17 18:00
This script might be a useful template to consider to collate "stats" on releases by crawling the github issue list: https://github.com/ipython/ipython/blob/master/tools/github_stats.py

**Comment by jypeter** [comment] 2015-02-18 10:24
After discovering yet another change I was not aware of in https://github.com/UV-CDAT/uvcdat/issues/999#issuecomment-74716288 I also insist that we really need to have a detailed and human-readable history of all the changes between each version! See the changelog they provide for VirtualBox for instance

https://www.virtualbox.org/wiki/Changelog

And the changes have to be easy to find from both the uv-cdat web site and the github wiki...

**Comment by doutriaux1** [comment] 2015-02-20 23:22
@mattben @chaosphere2112 do you think this is something you could handle?

**Comment by chaosphere2112** [comment] 2015-02-20 23:23
@doutriaux1 @mattben Yeah, I can take a look at this next week.

**Comment by doutriaux1** [comment] 2015-02-20 23:24
thanks @chaosphere2112 assigning this one to you then. Feel free to move to milestone 2.3

**Comment by chaosphere2112** [comment] 2015-03-02 18:20
I've found some software I can use to do this, there will be auto-generated notes with the 2.2 release; I think it'll have all issues that we've resolved since 2.1, and all pull requests.

**Comment by doutriaux1** [comment] 2015-03-02 19:06
@chaosphere2112 would it be possible to add as part of the build process, it would be great if you can get these everytime you build.

**Comment by chaosphere2112** [comment] 2015-03-02 19:08
Probably would be doable to get something plugged into Jenkins. I'll research that some.

**Comment by durack1** [comment] 2015-03-02 19:14
@chaosphere2112 this is great, looking forward to seeing this!

**Comment by aashish24** [comment] 2015-03-02 20:17
Adding it to build process is not that useful. Getting git logs and pull requests for release notes may not be helpful unless we are very careful with the pull request messagee

**Comment by chaosphere2112** [comment] 2015-03-02 22:12
@aashish24 @doutriaux1 I'm thinking that we can use the auto-generated release notes as a starting point; we can add commentary (or change the wording of the links) on things that are poorly worded or vague. Certainly listing every issue that's been fixed since the previous release is a good thing, along with links to them for the curious.

How about I get a sample of what the output looks like up on a page on uvcdat-dev.llnl.gov, and we can discuss what we want to do with it from there?

**Comment by durack1** [comment] 2015-03-02 22:33
@chaosphere2112 +1 from me, what you describe is exactly what I was hoping we could get.. I'll be keen to see this stuff when it's live!

**Comment by jypeter** [comment] 2015-03-03 14:01
:+1:  Yes, let's see how it looks like!

We may want to have both:
* an exhaustive list of all the changes (with helpful comments)
* a more user friendly list based on the exhaustive list, emphasizing the most important changes from the end user point of view

**Comment by doutriaux1** [comment] 2015-03-03 14:50
@chaosphere2112@ that sounds great.

**Comment by chaosphere2112** [comment] 2015-03-03 15:37
The tool I used to do the first draft wound up with a lot of noise; I'm going to write a script that gets a list of all merged pull requests, gets some info about those from the github API, and formats the output nicely. It's looking like we'll have a link in the bottom of the release notes that points to a page on the wiki with the changelog (since there's quite a lot in there, don't want to pollute the release notes). The notes themselves will list out all of the new features / major fixes for the release, and the changelog will just have the master list of everything. I've got most of the script done, just need to make some tweaks and I'll post a sample link here for people to look at in a bit.

**Comment by chaosphere2112** [comment] 2015-03-03 17:06
Here's a sample output– this is everything since the last tagged release in the repo.

http://uvcdat-dev.llnl.gov/changelog.html

The method I'm using to build this looks something like this:

1. I find most recent tag in the repo
2. I traverse parent commits from the current HEAD till I find the tag, and grab every commit that starts with "Merged pull request", the default commit message for merging pull requests on github
3. I look up the related pull request on GitHub and grab the title + url
4. I look up all commits associated with the pull request, and tally them up based on the author name
5. I look up any of the author names that are one word, to see if they're github users, and swap those out to the full name (deduplicating if someone– like me– does not have git correctly configured everywhere).
6. I sort based on commit count– whoever committed the most to a PR goes first, second most second, etc.

This can get tweaked pretty easily, and there's a lot of flexibility to do more stuff with the GitHub API.

**Comment by durack1** [comment] 2015-03-03 23:48
@chaosphere2112 here's another git implementation of changelog to consider: https://github.com/spyder-ide/spyder/wiki/Changelog

**Comment by jypeter** [comment] 2015-03-05 10:32
The list is impressive and quite promising, but is there a way to also have a direct link to the original issue?

eg for *fix 999 by Charles Doutriaux* you have a link to the pull request, but it would be convenient to also have a link to #999

**Comment by chaosphere2112** [comment] 2015-03-05 15:30
@jypeter Yeah, I can do that. I'm pulling the issue from GitHub already, to make it so those messages expand out to something more like "Fix #999: Multiple errors in vcs x.show by Charles Doutriaux". Should be easy enough to add ([Linked Issue](https://github.com/UV-CDAT/uvcdat/issues/999)) to the end.

**Comment by chaosphere2112** [comment] 2015-03-05 15:58
@jypeter @durack1 I updated the changelog to include links to associated issues– check it out at [uvcdat-dev.llnl.gov/changelog.html](http://uvcdat-dev.llnl.gov/changelog.html).

**Comment by jypeter** [comment] 2015-03-05 16:17
Looks pretty good to me!
We will also need a friendly summary for the end-user, that somebody knowledgeable can generate by looking at the exhaustive Changelog. **For example:**

* New features:
 * *execute x.interact() after plotting to a canvas in order to blahblah* <-- The kind of important change after 1.5.1

* New packages:
 * *Added vacumm NNNN*

* Updated packages:
 * *spydor was updated from 007 to 008*

**Comment by chaosphere2112** [comment] 2015-03-05 16:19
Yup, that's definitely going to be added. :+1:

**Comment by doutriaux1** [comment] 2015-03-05 18:47
@chaosphere2112 could we use the labels to try to to categorize these (we could have three level for each category: bug/enhancement/critical) and the categories could be the other labels?

**Comment by chaosphere2112** [comment] 2015-03-05 18:50
Yup, that would be super easy. I can do that :+1:

**Comment by aashish24** [comment] 2015-03-26 02:56
critical from the release point of view will not be that useful. I would suggest we only have 
bug/enh binary mode if anything. From the user point of view a clear one line what actually got fixed that affects the end-user is important. So let's say we fixed a contour masking related bug instead of saying:

* Fixed masking bug related to contour

is not that useful. But 

* Fixed a masking bug for 'nan' masking values that were resulting in a bad contour color

something like that is more useful.

**Comment by doutriaux1** [comment] 2015-03-26 03:22
Agreed and guilty

**Comment by durack1** [comment] 2015-03-31 16:09
@chaosphere2112 is there an option currently in place to acknowledge current unresolved issues - I'm thinking of #1125 and #1151 particularly here as these are highly relevant to users (at least me!), in my head it would be useful to link known issues set for fixing in 2.3

**Comment by chaosphere2112** [comment] 2015-03-31 16:16
Not currently… I could attach a link at the bottom to “Upcoming Development” that links to all open issues for 2.3. Or maybe we can reassign important issues to 2.2.1 or something like that? I might be able to get a list of all issues that have been moved from 2.2 to 2.3 and are still open. Will have to poke at the API a bit.

**Comment by durack1** [comment] 2015-03-31 16:20
What I was thinking was similar to what Firefox owns up to: https://www.mozilla.org/en-US/firefox/36.0.4/releasenotes/ - so the #1125 and #1151 are issues that 2.2 will still likely include, but they are planned to be resolved quickly..

**Comment by chaosphere2112** [comment] 2015-03-31 16:21
Yeah, we can do something like that, but probably not automatically; it’ll have to be manually curated.

**Comment by durack1** [comment] 2015-03-31 16:25
@chaosphere2112 maybe then only issues with "critical" or "high" labels - @doutriaux1 would you consider #1125 and #1151 worthy of these labels?

If a high priority label can then be assigned, I'd imagine it would be possible to automate their generation?

**Comment by chaosphere2112** [comment] 2015-03-31 16:26
Yup, that’d work fine by me.

**Comment by chaosphere2112** [comment] 2015-04-03 21:06
@durack1 @aashish24 @doutriaux1 @jypeter 

http://uvcdat-dev.llnl.gov/changelog.html

I've just updated the dev site's changelog, using a new-and-improved script for yanking stuff out of GitHub's API to sort out what goes where. Any uncategorized Pull Requests are currently not included, and I haven't yet reimplemented the "credit" part of the previous iteration of the changelog. Also, there are currently four \*'s when no Bug/Enhancement label is given to an issue, but since they're all listed with the link to the bug next to them, it should be easy enough to go back and clean up all of the issues.

Still to do:

1. Add back in the "credit" for a bug fix / pull request by digging through the commits and PR records to get that all squared away
2. Write the change summary mentioned by @jypeter 
3. ???

**Comment by aashish24** [comment] 2015-04-05 23:14
hi @chaosphere2112 thanks. Can we clean up this? Would it be possible to make it editable somehow?

**Comment by chaosphere2112** [comment] 2015-04-06 12:59
It generates markdown which I stuck on the website. If we want to host this on the wiki, that would work too. The repo is UV-CDAT/changelogger, though I can get a copy of this in the wiki for you to mess with. We're off at Livermore today ("Spring Holiday"), by the way.

**Comment by aashish24** [comment] 2015-04-07 00:26
Okay, I can push a branch on the changelogger then. 

- Aashish

**Comment by durack1** [comment] 2015-05-11 17:28
@chaosphere2112 some of the labelling has been cleaned up more recently than the last time it appears your page has been updated - could you regenerate this from the most recent repo status and see if the duplicates etc have been removed?

**Comment by chaosphere2112** [comment] 2015-05-11 17:29
Sure, I'll do that in a bit.

**Comment by chaosphere2112** [comment] 2015-05-11 19:44
@durack1 
I've updated the changelog on the dev site. http://uvcdat-dev.llnl.gov/changelog.html

@aashish24 Want me to stick this on a wiki page?

**Comment by durack1** [comment] 2015-05-11 19:48
@chaosphere2112 would it be more helpful to fix the labels assigned to each of these issues/PRs within the github issue tracker and rerun before hand editing?

**Comment by chaosphere2112** [comment] 2015-05-11 19:51
@durack1 If you don't mind, then sure! It's pretty quick to generate the changelog (well, a minute or two, but only because it makes like a thousand http requests), and having the metadata all properly set up would be a nice thing.

**Comment by durack1** [comment] 2015-05-11 19:56
@chaosphere2112 ok have another go.. You've also got a couple of cases where duplicates have occurred, so e.g.
https://github.com/UV-CDAT/uvcdat/issues/1049

It's most likely when you have a "gatekeeper" issue, which is also listed under one of the submodules..

**Comment by chaosphere2112** [comment] 2015-05-11 20:08
@durack1 OK, fixed those; I'm going to spend a little time making sure that PRs that refer to Issues don't get double counted (just have a link to the relevant issue and PR on the same line item)

**Comment by durack1** [comment] 2015-05-11 20:09
@chaosphere2112 it might also be an issue for "critical" labelled issues and also the combo "Documentation" and "Website" https://github.com/UV-CDAT/uvcdat/issues/1136

**Comment by durack1** [comment] 2015-05-11 20:11
@chaosphere2112 and just a comment, now you have bug/enhancement for each issue listed you might want to order these, so b "bugs" then e "enhancement" or similar..

**Comment by chaosphere2112** [comment] 2015-05-11 20:11
@durack1 Critical should be handled correctly (I categorize based on severity separately), but documentation/website probably dupes. Sorting by type would be good :+1: I'll do that.

**Comment by durack1** [comment] 2015-05-11 20:13
@chaosphere2112 and regarding PRs.. I think labels should only really be associated with the issue, and hopefully each PR has an issue that it fixes..? I know this isn't always the case, but it would be good practice to order things this way.. And will just require folks creating issues to label these correctly, and indicate issue numbers in the PR too

**Comment by durack1** [comment] 2015-05-11 20:15
@chaosphere2112 just from a style point of view here is another: https://github.com/spyder-ide/spyder/releases/tag/v2.3.4 not that I'm advocating changing anything..

**Comment by chaosphere2112** [comment] 2015-05-11 20:16
@durack1 I agree that labels should only be on issues; I'm just going to make it so that the issues and the PRs show up in the same place. Github's API treats both as an "issue", which is why they show up on multiple lines right now. The main reason I would want to include PRs without associated issues is for things like #1081, which was a completely new feature that had no associated issue.

**Comment by chaosphere2112** [comment] 2015-05-11 20:18
I also tend to err on the side of not requiring additional steps from the developers for something that I can hopefully solve with some simple de-duplication based on references to specific issues (which is the common practice already).

**Comment by chaosphere2112** [comment] 2015-05-11 20:18
That said, I can shove the non-issue-associated PRs down onto the bottom as a separate category like in the Spyder changelog.

**Comment by durack1** [comment] 2015-05-11 20:19
@chaosphere2112 another double counter https://github.com/UV-CDAT/uvcdat/issues/615

**Comment by durack1** [comment] 2015-05-11 20:20
@chaosphere2112 I think the "orphan" PR section would be a good idea.. Same goes with your other tweaks/suggestions..

**Comment by chaosphere2112** [comment] 2015-05-11 20:21
:+1:  Will do, then.

**Comment by chaosphere2112** [comment] 2015-05-11 21:44
@durack1 Looks like most of the orphaned PRs aren't tagged with any milestone, so they don't show up in the automatic report currently... I'm going to add a run over all PRs that have targeted a branch (in this case, `release`) and add them to the list.

**Comment by durack1** [comment] 2015-05-11 21:48
@chaosphere2112 would it be possible to set a date range, so since the [2.1.0](https://github.com/UV-CDAT/uvcdat/releases/tag/2.1.0) release back on 14th Jan and grab every other PR since then?

**Comment by chaosphere2112** [comment] 2015-05-11 21:49
Yeah, that should be fine. I'm going to do the filter by branch as well, though, because we've got stuff in master that isn't going out in the release.

**Comment by chaosphere2112** [comment] 2015-05-11 21:53
Actually, @durack1, if I do it by date range, I could just exclude everything that's been explicitly tagged 2.3; that should be quite accurate (and easy!).

**Comment by durack1** [comment] 2015-05-11 21:58
@chaosphere2112 it would also be an opportunity to fill out a "planned changes" or similar with 2.3 tagged PRs that are already in the queue, i.e. #915, #1074, #1129, #1130, #1131, #1253 ... Not sure if this is worth it, or whether future milestone PRs will be numerous enough to list (in this and future releases).. May as well show folks that action is underway..

**Comment by chaosphere2112** [comment] 2015-05-11 23:19
@durack1 OK, I've got most of what we've discussed; a complete(-ish) list of issues/PRs since 2.1. Where possible, I've moved PRs to be associated with the bug/enhancement they mention. I sort by bug/enhancement, list Known Bugs and Merged Pull Requests below all of the resolved issues. I do not yet have "Planned Work"; I tend to think we should leave that off for now, as we don't necessarily want to commit to completing those things until we know for sure what's going on, but @williams13 will probably have to weigh in on that. http://uvcdat-dev.llnl.gov/changelog.html has the most recent version (found few more issues that are unlabeled).

**Comment by durack1** [comment] 2015-05-11 23:35
@chaosphere2112 ok great, I've just had a look at the issues without a "bug" "enhancement" label and added them where appropriate so another pass should pull this in.. And it might be ready to be migrated across to the wiki for hand-editing by @aashish24 and @doutriaux1

**Comment by durack1** [comment] 2015-05-11 23:59
@chaosphere2112 with the "orphan" PRs, is there any apparent order to their listing? As you've got the PR numbers there I'd err toward listing these in ascending (lowest/oldest at the top to highest/newest) or descending order..

**Comment by chaosphere2112** [comment] 2015-05-12 02:57
@durack1 Nope, they're just in whatever order Github handed them to me in (I think sorted by last interacted with or something like that). I'll sort them by number.

**Comment by chaosphere2112** [comment] 2015-05-12 14:47
@durack1 OK, I added a check to make sure that pull requests/issues are properly filtered to only this release, and I've sorted the PRs by number. It's up on the dev site for examination: http://uvcdat-dev.llnl.gov/changelog.html

**Comment by durack1** [comment] 2015-05-12 22:39
@chaosphere2112 great, it's getting close.. I'm not sure if you want to include bugs that have been labeled "unconfirmed" or "wontfix" as with #678, #859, #1054 and #1134. You've already re-labeled things with "bug" I see #960, #966, #1088 and #1104

It also seems that bugs that are known and labeled against the 2.3 milestone aren't listing in the "Known Bugs" heading like #961 - I wonder if this should include more of the known issues?

**Comment by chaosphere2112** [comment] 2015-05-13 14:24
@durack1 I'm skipping wontfix, currently, and I just added "unconfirmed" to the list of labels to skip. Currently, the only issues getting stuck into "Known Bugs" are those marked Critical or High Priority, as you suggested [above](https://github.com/UV-CDAT/uvcdat/issues/913#issuecomment-88156771). I can tweak that to add all open bugs easily enough, though. Should I?

**Comment by durack1** [comment] 2015-05-13 14:50
@chaosphere2112 good question (add all known bugs), maybe give it a go and see what it looks like.. The current listing of just 2 known bugs is a little light I think, in particular when we know there are more issues in the system that should be fixed fairly promptly after 2.2 is released..

**Comment by chaosphere2112** [comment] 2015-05-13 15:51
Alright, added the "Other Issues" section, which looks like a pretty reasonable length. I also came up with a metric to remove old issues that were recently modified/closed/whatever– if the last comment was before the "since" date, it's probably a quite old bug and doesn't need to be reported (because I was getting #219 to show up in the changelog, and that definitely wasn't a recent fix). Same URL.

**Comment by durack1** [comment] 2015-05-13 16:00
@chaosphere2112 ok, well this looks good to me.. I suppose you await the 2.2 tag to be finalised, and then push the final version across to the wiki for hand editing if @aashish24 and @doutriaux1 feel like this is necessary..?

**Comment by chaosphere2112** [comment] 2015-05-13 16:01
Sounds good to me. @aashish24 @doutriaux1, here's the semi-final draft of the changelog: http://uvcdat-dev.llnl.gov/changelog.html

**Comment by durack1** [comment] 2015-05-21 23:34
@chaosphere2112 @doutriaux1 @aashish24 I assume this issue can now be closed?

**Comment by aashish24** [comment] 2015-05-22 12:59
yes :smile:

**Closed by aashish24** 2015-05-22 12:59 UTC
Labels: Documentation, Enhancement
